### ISSUE TITLE
Render HTML page.

### ISSUE THREAD

**Issue by proofit404** [proofit404/lime#111]

**Comment by 0pdd** [comment]
@proofit404 2 puzzles [#113](https://github.com/proofit404/lime/issues/113), [#114](https://github.com/proofit404/lime/issues/114) are still not solved.

**Comment by 0pdd** [comment]
@proofit404 2 puzzles [#113](https://github.com/proofit404/lime/issues/113), [#117](https://github.com/proofit404/lime/issues/117) are still not solved; solved: [#114](https://github.com/proofit404/lime/issues/114).

**Comment by 0pdd** [comment]
@proofit404 the puzzle [#113](https://github.com/proofit404/lime/issues/113) is still not solved; solved: [#114](https://github.com/proofit404/lime/issues/114), [#117](https://github.com/proofit404/lime/issues/117).

**Comment by 0pdd** [comment]
@proofit404 all 3 puzzles are solved here: [#113](https://github.com/proofit404/lime/issues/113), [#114](https://github.com/proofit404/lime/issues/114), [#117](https://github.com/proofit404/lime/issues/117).
