### ISSUE TITLE
Drop SQL Alchemy.

### ISSUE THREAD

**Issue by proofit404** [proofit404/lime#121]
We will use raw SQL.

**Comment by 0pdd** [comment]
@proofit404 2 puzzles [#125](https://github.com/proofit404/lime/issues/125), [#126](https://github.com/proofit404/lime/issues/126) are still not solved.

**Comment by 0pdd** [comment]
@proofit404 2 puzzles [#198](https://github.com/proofit404/limebot/issues/198), [#199](https://github.com/proofit404/limebot/issues/199) are still not solved.

**Comment by 0pdd** [comment]
@proofit404 the puzzle [#198](https://github.com/proofit404/limebot/issues/198) is still not solved; solved: [#199](https://github.com/proofit404/limebot/issues/199).
